articles/urls.py
from django.urls import path
from . import views
from .sitemaps import ArticleSitemap
from .feeds import LatestArticlesFeed
from django.contrib.sitemaps.views import sitemap
app_name = 'articles'

sitemaps = {
    'articles': ArticleSitemap,
}
urlpatterns = [
    path('',views.ArticleListView.as_view(),name='list'),
    path('<uuid:pk>',
         views.ArticleDetailView.as_view(), name='details'),
    path('<uuid:pk>/edit', views.ArticleUpdateView.as_view(), name='edit'),
    path('<uuid:pk>/delete', views.ArticleDeleteView.as_view(), name='delete'),
    path('create',views.ArticleCreateView.as_view(),name = 'create'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('feed', LatestArticlesFeed(), name="feed"),
    path('search', views.article_search,name = "search"),
    path('react', views.react, name ="react")
    
]

newspaper_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
    path('articles/', include('articles.urls',namespace='article')),
]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from articles import views as article_views

urlpatterns = [
    #path('',views.Home.as_view(),name = 'home'),
    path('', article_views.article_list_with_ajax_pagination, name='home'),
    path('about',views.About.as_view(),name = 'about'),
    path('contact',views.Contact.as_view(),name = 'contact'),
    path('categories/<int:pk>',views.Category.as_view(),name = 'category'),
   # path('tags/<slug:tag_slug>/',views.tag,name = 'tag'),
    path('tags/<int:pk>', views.Tagged.as_view(), name='tag'),
]

articles/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils import timezone
import uuid
import readtime
from django.utils.translation import ugettext_lazy as _
from taggit.managers import TaggableManager
from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase
from .managers import PublishedManager
# Create your models here.


class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    # If you only inherit GenericUUIDTaggedItemBase, you need to define
    # a tag field. e.g.
    # tag = models.ForeignKey(Tag, related_name="uuid_tagged_items", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")


class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Article(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    body = models.TextField()
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = TaggableManager(through=UUIDTaggedItem)
    image = models.ImageField(upload_to='images/', blank=True)
    views = models.IntegerField(default=0)
    users_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='articles_liked', blank=True)
    objects = models.Manager()
    published_article = PublishedManager()
    class Meta:
        ordering = ('-published',)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

    def pub(self):
        return self.published.strftime('%b %e %Y')

    def year(self):
        return self.published.strftime('%Y')

    def month(self):
        return self.published.strftime('%b')

    def day(self):
        return self.published.strftime('%d')

    def countWords(self):
        return readtime.of_text(self.body)

    def get_absolute_url(self):
        return reverse('article:details', args=[str(self.id)])


class Comment(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.article}'

articles/forms.py
from django import forms
from .models import *


class ArticleCreateForm(forms.ModelForm):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    category = forms.ModelChoiceField(queryset=Category.objects.all())
    status = forms.ChoiceField(choices=STATUS_CHOICES)

    class Meta:
        model = Article
        fields = {'title', 'body', 'category', 'image', 'tags', 'status'}
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input--style-5'}),
            'body': forms.Textarea(attrs={'class': 'input--style-5', 'col': 40, 'row': 20}),
            'status': forms.TextInput(attrs={'class': 'input--style-5'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'name', 'email', 'body'}

class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control form-control-sm mr-3 w-75 my-5',
               'placeholder':'Search'}))

articles/views.py
from django.shortcuts import render, redirect
from .forms import ArticleCreateForm, CommentForm, SearchForm
from .models import Category, Article, Comment
from django.views.generic import (ListView, CreateView,
                                  UpdateView, DeleteView, DetailView, FormView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.core.exceptions import PermissionDenied
from django.views.generic.edit import FormMixin
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from common.decorators import ajax_required
from django.core.paginator import (Paginator, EmptyPage, 
                                   PageNotAnInteger)

@ajax_required
@login_required
@require_POST
def react(request):
    article_id = request.POST.get('id')
    action = request.POST.get('action')
    if article_id and action:
        try:
            article = Article.objects.get(id=article_id)
            if action == "like":
                article.users_like.add(request.user)
            else:
                article.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})    
        except:
            pass    
    return JsonResponse({'status':'error'})

def article_list_with_ajax_pagination(request):
    articles = Article.published_article.all()
    paginator = Paginator(articles, 1)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
            # If page is not an integer deliver the first page
        articles = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # If the request is AJAX and the page is out of range
            # return an empty page
            return HttpResponse('')
        # If page is out of range deliver last page of results
        articles = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                        'pages/list_ajax.html',
                        {'articles': articles})
    return render(request,
                    'pages/home.html',
                    {'articles': articles})

    
    

def article_search(request):
    form = SearchForm()
    query = None
    result = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            search_vector = SearchVector('title', weight='A') + \
                SearchVector('body', weight='A') + \
                SearchVector('author', weight='A')
            query = form.cleaned_data['query']
            search_query = SearchQuery(query)
            result = Article.published_article.annotate(
                search=search_vector, rank=SearchRank(search_vector, search_query)).filter(rank__gte=0.3) \
                .order_by('-rank')

    return render(request, 'articles/search.html', {'form': form, 'query': query, 'result': result})


class ArticleListView(ListView):
    model = Article
    context_object_name = 'articles'
    template_name = 'articles/article_list.html'
    paginate_by = 3


class ArticleDetailView(FormMixin, DetailView):
    model = Article
    template_name = 'articles/article_details.html'
    form_class = CommentForm

    def get_success_url(self):
        return reverse_lazy('articles:details', args=[self.object.id])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = context['article'].comments.filter(active=True)
        context['comment_form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        new_comment = form.save(commit=False)
        new_comment.article = self.object
        new_comment.save()
        return super(ArticleDetailView, self).form_valid(form)


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    form_class = ArticleCreateForm
    template_name = 'articles/article_create.html'
    login_url = 'login'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleCreateForm
    template_name = 'articles/article_update.html'
    login_url = 'login'

    def dispatch(self, request, *args, **kwargs):  # new
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    form_class = ArticleCreateForm
    success_url = reverse_lazy('home')

    def dispatch(self, request, *args, **kwargs):  # new
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

articles/templates/articles/article_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block externals %} 
<!-- Icons font CSS-->
<link
  href="{% static 'articles/vendor/mdi-font/css/material-design-iconic-font.min.css' %}"
  rel="stylesheet"
  media="all"
/>
<link
  href="{% static 'articles/vendor/font-awesome-4.7/css/font-awesome.min.css' %}"
  rel="stylesheet"
  media="all"
/>
<!-- Font special for pages-->
<link
  href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i"
  rel="stylesheet"
/>

<!-- Vendor CSS-->
<link
  href="{% static 'articles/vendor/select2/select2.min.css' %}"
  rel="stylesheet"
  media="all"
/>
<link
  href="{% static 'articles/vendor/datepicker/daterangepicker.css' %}"
  rel="stylesheet"
  media="all"
/>

<!-- Main CSS-->
<link
  href="{% static 'articles/css/main2.css' %}"
  rel="stylesheet"
  media="all"
/>

{% endblock externals %} {% block content %}
<div class="page-wrapper bg-gra-03 p-t-130 p-b-50">
  <div class="wrapper wrapper--w790">
    <div class="card card-5">
      <div class="card-heading">
        <h2 class="title">Create Article</h2>
      </div>
      <div class="card-body">
        <form
          method="POST"
          action="{% url 'article:create'%}"
          enctype="multipart/form-data"
        >
        {% csrf_token %}
          <div class="form-row m-b-55">
            <div class="name">Title</div>
            <div class="value">
              <div class="row row-space">
                <div class="col">
                  <div class="input-group-desc">
                    {{form.title | as_crispy_field}}
                    
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-row m-b-55">
            <div class="name">Category</div>
            <div class="value">
              <div class="input-group">
                <div class="rs-select2 js-select-simple select--no-search ">
                {{form.category | as_crispy_field}}
                 <div class="select-dropdown"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-row">
            <div class="name">Image</div>
            <div class="value">
              <div class="input-group">
                {{form.image | as_crispy_field}}
              </div>
            </div>
          </div>
          <div class="form-row m-b-55">
            <div class="name">Body</div>
            <div class="value">
              <div class="row row-space">
                <div class="col">
                  <div class="input-group-desc">
                    {{form.body | as_crispy_field}}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-row m-b-55">
            <div class="name">Tags</div>
            <div class="value">
              <div class="row row-space">
                <div class="col">
                  <div class="input-group-desc" data-role="tagsinput">
                    {{form.tags | as_crispy_field}}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-row m-b-55">
            <div class="name">Status</div>
            <div class="value">
              <div class="row row-space">
                <div class="col">
                  <div class="input-group-desc">
                    {{form.status | as_crispy_field }}
                  </div>
                </div>
              </div>
            </div>
          </div>
         

          <div>
            <button class="btn btn--radius-2 btn--red" type="submit">
              Create
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %} {% block externalScripts %}
<script src="{% static 'articles/vendor/jquery/jquery.min.js' %}"></script>
<!-- Vendor JS-->
<script src="{% static 'articles/vendor/select2/select2.min.js' %}"></script>
<script src="{% static 'articles/vendor/datepicker/moment.min.js' %}"></script>
<script src="{% static 'articles/vendor/datepicker/daterangepicker.js' %}"></script>

<!-- Main JS-->
<script src="{% static 'articles/js/global.js' %}"></script>
{% endblock externalScripts %}

articles/templates/articles/article_details.html
{% extends "base.html" %} 
{% load staticfiles %}
 {% load crispy_forms_tags %}
{% load%}
{%load article_tags %} {% block externals %}
<style>
  .hidden {
    display: none;
  }
</style>
{% endblock externals %} {% block content %}
<section
  class="hero-wrap hero-wrap-2 js-fullheight"
  style="background-image: url('static/images/bg_1.jpg');"
  data-stellar-background-ratio="0.5"
>
  <div class="overlay"></div>
  <div class="container">
    <div
      class="row no-gutters slider-text js-fullheight align-items-end justify-content-center"
    >
      <div class="col-md-9 ftco-animate pb-5 text-center">
        <h1 class="mb-3 bread">{{article.title}}</h1>
        <p class="breadcrumbs">
          <span class="mr-2"
            ><a href="{% url 'home' %}"
              >Home <i class="ion-ios-arrow-forward"></i></a
          ></span>
          <span class="mr-2"
            ><a href="url 'article:list'"
              >Articles <i class="ion-ios-arrow-forward"></i></a
          ></span>
          <span><i class="ion-ios-arrow-forward"></i></span>
        </p>
      </div>
    </div>
  </div>
</section>

<section class="ftco-section ftco-degree-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 ftco-animate">
        <p class="mb-5">
          <img src="{{article.image.url}}" alt="" class="img-fluid" />
        </p>
        <p class="mb-5">{{article.body|linebreaks}}</p>
        <div class="tag-widget post-tag-container mb-5 mt-5">
          <div class="tagcloud">
            {% for i in article.tags.all %}
            <a href="{% url 'tag' i.id %}" class="tag-cloud-link">{{i.name}}</a>

            {% endfor %}
          </div>
        </div>
        <span class="count">
        <span class="total">{{ article.users_like.count }}</span>
        like{{ article.users_like.count|pluralize }}
        </span>

        <a href="#" data-id="{{ article.id }}" 
        data-action="{% if request.user in   article.users_like.all %}
        un{% endif %}like"
        class="react btn btn-success"
          >
          {% if request.user not in article.users_like.all %}
          Like
          {% else %}
          Unlike
          {% endif %}

          </a>

        <div class="about-author d-flex p-4 bg-light">
          <div class="bio mr-5">
            <img
              src="{% static 'images/person_1.jpg' %}"
              alt="Image placeholder"
              class="img-fluid mb-4"
            />
          </div>
          <div class="desc">
            <h3 class="font-weight-bold">{{article.author}}</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus
              itaque, autem necessitatibus voluptate quod mollitia delectus aut,
              sunt placeat nam vero culpa sapiente consectetur similique,
              inventore eos fugit cupiditate numquam!
            </p>
          </div>
        </div>

        {% with comments.count as total_comments %}
        <h2>
          {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
        {% endwith %} {% for comment in comments %}
        <div class="comment">
          <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
          </p>
          {{ comment.body|linebreaks }}
        </div>
        {% empty %}
        <p>There are no comments yet.</p>
        {% endfor %} {% if user.is_authenticated %}
        <h2 class="font-weight-bold">Add a new comment</h2>
        <form method="post">
          {% csrf_token %} {{ comment_form|crispy }} {% csrf_token %}
          <p><input type="submit" value="Add comment" /></p>
        </form>

        {% endif %}
      </div>
      <!-- .col-md-8 -->
      <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
        <div class="sidebar-box">
          <form action="#" class="search-form">
            <div class="form-group">
              <span class="icon icon-search"></span>
              <input
                type="text"
                class="form-control"
                placeholder="Type a keyword and hit enter"
              />
            </div>
          </form>
        </div>
        <div class="sidebar-box ftco-animate">
          <div class="categories">
            <h3>Categories</h3>
            {% for category in categories %}
            <li>
              <a href="{% url 'category' category.id %}"
                >{{category.name}} <span class="ion-ios-arrow-forward"></span
              ></a>
            </li>
            {% endfor %}
          </div>
        </div>

        {% latest_articles %} {% popular_articles %}
        <div class="sidebar-box ftco-animate">
          <h3>Tag Cloud</h3>
          <div class="tagcloud">
            {% for tag in tags|slice:':5' %}
            <a href="{% url 'tag' tag.id %}" class="tag-cloud-link">{{tag}}</a>
            {% endfor %}
          </div>
        </div>

        <div class="sidebar-box ftco-animate">
          <h3>Paragraph</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus
            itaque, autem necessitatibus voluptate quod mollitia delectus aut,
            sunt placeat nam vero culpa sapiente consectetur similique,
            inventore eos fugit cupiditate numquam!
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- .section -->

{% endblock  %} 
{% block domready %} 
  $('a.react').click(function(e)
  {
  e.preventDefault();
$.post('{% url "articles:react" %}',
{
id: $(this).data('id'), 
action: $(this).data('action')

},
function(data){
if (data['status'] == 'ok')
{
var previous_action = $('a.react').data('action');
// toggle data-action
$('a.react').data('action', previous_action == 'like' ?
'unlike' : 'like');
// toggle link text
$('a.react').text(previous_action == 'like' ? 'Unlike' :
'Like');
// update total likes
var previous_likes = parseInt($('span.count .total').
text());
$('span.count .total').text(previous_action == 'like' ?
previous_likes + 1 : previous_likes - 1);
}
}
);
});
{% endblock %}

articles/templates/articles/article_update.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% load article_tags %} 
{% block externals %} 
<!-- Icons font CSS-->
<link
  href="{% static 'articles/vendor/mdi-font/css/material-design-iconic-font.min.css' %}"
  rel="stylesheet"
  media="all"
/>
<link
  href="{% static 'articles/vendor/font-awesome-4.7/css/font-awesome.min.css' %}"
  rel="stylesheet"
  media="all"
/>
<!-- Font special for pages-->
<link
  href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i"
  rel="stylesheet"
/>

<!-- Vendor CSS-->
<link
  href="{% static 'articles/vendor/select2/select2.min.css' %}"
  rel="stylesheet"
  media="all"
/>
<link
  href="{% static 'articles/vendor/datepicker/daterangepicker.css' %}"
  rel="stylesheet"
  media="all"
/>

<!-- Main CSS-->
<link
  href="{% static 'articles/css/main2.css' %}"
  rel="stylesheet"
  media="all"
/>

{% endblock externals %} {% block content %}
<div class="page-wrapper bg-gra-03 p-t-130 p-b-50">
  <div class="wrapper wrapper--w790">
    <div class="card card-5">
      <div class="card-heading">
        <h2 class="title">Edit Article</h2>
      </div>
      <div class="card-body">
        <form method="POST" enctype="multipart/form-data" action="{% url 'article:edit' article.id %}">
          {% csrf_token %}
          <div class="form-row m-b-55">
            <div class="name">Title</div>
            <div class="value">
              <div class="row row-space">
                <div class="col">
                  <div class="input-group-desc">
                    <!-- <input class="input--style-5" type="text" name="title"   required/> -->
                    {{form.title | as_crispy_field}}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-row">
            <div class="name">Category</div>
            <div class="value">
              <div class="input-group">
                <div class="rs-select2 js-select-simple select--no-search">
                  {{form.category | as_crispy_field}}
                  <div class="select-dropdown"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-row">
            <div class="name">Image</div>
            <div class="value">
              <div class="input-group">
                <!-- <input type="file" class="form-control-file" id="image" name="image" required> -->
                {{form.image | as_crispy_field}}
              </div>
            </div>
          </div>
          <div class="form-row m-b-55">
            <div class="name">Body</div>
            <div class="value">
              <div class="row row-space">
                <div class="col">
                  <div class="input-group-desc">
                    <!-- <textarea name="body" class="input--style-5" id="" cols="40" rows="20" required></textarea> -->
                    {{form.body | as_crispy_field}}
                  </div>
                </div>
              </div>
            </div>
          </div>
           <div class="form-row m-b-55">
            <div class="name">Tags</div>
            <div class="value">
              <div class="row row-space">
                <div class="col">
                  <div class="input-group-desc" data-role="tagsinput">
                    {{form.tags | as_crispy_field}}
                  </div>
                </div>
              </div>
            </div>
          </div> 
            <div class="form-row m-b-55">
            <div class="name">Status</div>
            <div class="value">
              <div class="row row-space">
                <div class="col">
                  <div class="input-group-desc">
                    {{form.status | as_crispy_field }}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <button class="btn btn--radius-2 btn--red" type="submit">
              Update
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %} {% block externalScripts %}
<script src="{% static 'articles/vendor/jquery/jquery.min.js' %}"></script>
<!-- Vendor JS-->
<script src="{% static 'articles/vendor/select2/select2.min.js' %}"></script>
<script src="{% static 'articles/vendor/datepicker/moment.min.js' %}"></script>
<script src="{% static 'articles/vendor/datepicker/daterangepicker.js' %}"></script>

<!-- Main JS-->
<script src="{% static 'articles/js/global.js' %}"></script>
{% endblock externalScripts %}

articles/templates/articles/latest_articles.html
<div class="sidebar-box ftco-animate">
          <h3>Latest Articles</h3>
          
          {% for article in latest %}
            
          <div class="block-21 mb-4 d-flex">
              <a
              href="{% url 'article:details' article.id  %}"
              class="blog-img mr-4"
              style="background-image: url({{article.image.url}});"
            ></a>
            <div class="text">
              <h3 class="heading">
                <a href="{% url 'article:details' article.id  %}"
                  >{{article.title}}</a
                >
              </h3>
              <div class="meta">
                <div>
                  <a href="{% url 'article:details' article.id  %}"
                    ><span class="icon-calendar"></span>{{article.published}}</a
                  >
                </div>
                <div>
                  <a href="#"><span class="icon-person"></span> {{article.author}}</a>
                </div>
                <div>
                  <a href="#"><span class="icon-chat"></span> {{article.comments.count}}</a>
                </div>
              </div>
            </div>
         
        </div>
         {% endfor %}
</div>

articles/templates/articles/popular_articles.html
<div class="sidebar-box ftco-animate">
          <h3>Most Commented Articles</h3>
          
          {% for article in popular %}
           
          <div class="block-21 mb-4 d-flex">
              <a
              href="{% url 'article:details' article.id  %}"
              class="blog-img mr-4"
              style="background-image: url({{article.image.url}});"
            ></a>
            <div class="text">
              <h3 class="heading">
                <a href="{% url 'article:details' article.id  %}"
                  >{{article.title}}</a
                >
              </h3>
              <div class="meta">
                <div>
                  <a href="{% url 'article:details' article.id  %}"
                    ><span class="icon-calendar"></span>{{article.published}}</a
                  >
                </div>
                <div>
                  <a href="#"><span class="icon-person"></span> {{article.author}}</a>
                </div>
                <div>
                  <a href="#"><span class="icon-chat"></span> {{article.comments.count}}</a>
                </div>
              </div>
            </div>
         
        </div>
         {% endfor %}
</div>

articles/templates/articles/search.html
{% extends "base.html" %}
{% load article_tags %} 
{% load crispy_forms_tags %}
{% load staticfiles %} {% block content %}
<div
  class="hero-wrap js-fullheight"
  style="background-image: url('static/images/bg_1.jpg');"
  data-stellar-background-ratio="0.5"
>
  <div class="overlay"></div>
  <div class="container">
    <div
      class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
      data-scrollax-parent="true"
    >
      <div class="col-md-12 ftco-animate">
        <h2 class="subheading">Hello! Welcome to</h2>
        <h1 class="mb-4 mb-md-0">News24</h1>
        <div class="row">
          <div class="col-md-7">
            <div class="text">
              <p>
                Far far away, behind the word mountains, far from the countries
                Vokalia and Consonantia, there live the blind texts. Separated
                they live in Bookmarksgrove right at the coast of the Semantics,
                a large language ocean.
              </p>
              <div class="mouse">
                <a href="#section" class="mouse-icon">
                  <div class="mouse-wheel">
                    <span class="ion-ios-arrow-round-down"></span>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <h1 class="font-weight-bold mt-3 mb-2 text-lg-center">Search for Articles</h1>
  <form
    class="form-inline d-flex justify-content-center md-form form-sm"
    method="get"
    action="{% url 'article:search'%}"
  >
    <!-- <input class="form-control form-control-sm mr-3 w-75 my-5" type="text" placeholder="Search"
    aria-label="Search"> -->
    {{form.query}}
    <i class="fas fa-search my-5" aria-hidden="true"></i>
  </form>
  {% if query %}
  <h2 class="font-weight-bold text-center">Articles containing <span style="color:blue">{{query}}</span></h2>
  {% if result.count == 0 %}
  <h3 class="font-weight-bold" style="color: red;">No Results found</h3>
  {% else %}
  <h3 class="font-weight-bold" style="color:green">
    Found {{result.count}} Result{{result.count|pluralize}}
  </h3>
  {% for res in result %}
        <div class="mb-4">
        <h4> <a href="{{ res.get_absolute_url }}"> {{res.title}}</a></h4>
        {{res.body|truncatewords_html:5}}
        </div>
  {% endfor %}
  {% endif %} {% endif %}
</div>
{% endblock content %}