articles/urls.py
from django.urls import path
from . import views
from .sitemaps import ArticleSitemap
from .feeds import LatestArticlesFeed
from django.contrib.sitemaps.views import sitemap
app_name = 'articles'

sitemaps = {
    'articles': ArticleSitemap,
}
urlpatterns = [
    path('',views.ArticleListView.as_view(),name='list'),
    path('<uuid:pk>',
         views.ArticleDetailView.as_view(), name='details'),
    path('<uuid:pk>/edit', views.ArticleUpdateView.as_view(), name='edit'),
    path('<uuid:pk>/delete', views.ArticleDeleteView.as_view(), name='delete'),
    path('create',views.ArticleCreateView.as_view(),name = 'create'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('feed', LatestArticlesFeed(), name="feed"),
    path('search', views.article_search,name = "search"),
    path('react', views.react, name ="react")
    
]

newspaper_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
    path('articles/', include('articles.urls',namespace='article')),
]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from articles import views as article_views

urlpatterns = [
    #path('',views.Home.as_view(),name = 'home'),
    path('', article_views.article_list_with_ajax_pagination, name='home'),
    path('about',views.About.as_view(),name = 'about'),
    path('contact',views.Contact.as_view(),name = 'contact'),
    path('categories/<int:pk>',views.Category.as_view(),name = 'category'),
   # path('tags/<slug:tag_slug>/',views.tag,name = 'tag'),
    path('tags/<int:pk>', views.Tagged.as_view(), name='tag'),
]

articles/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils import timezone
import uuid
import readtime
from django.utils.translation import ugettext_lazy as _
from taggit.managers import TaggableManager
from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase
from .managers import PublishedManager
# Create your models here.


class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    # If you only inherit GenericUUIDTaggedItemBase, you need to define
    # a tag field. e.g.
    # tag = models.ForeignKey(Tag, related_name="uuid_tagged_items", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")


class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Article(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    body = models.TextField()
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = TaggableManager(through=UUIDTaggedItem)
    image = models.ImageField(upload_to='images/', blank=True)
    views = models.IntegerField(default=0)
    users_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='articles_liked', blank=True)
    objects = models.Manager()
    published_article = PublishedManager()
    class Meta:
        ordering = ('-published',)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

    def pub(self):
        return self.published.strftime('%b %e %Y')

    def year(self):
        return self.published.strftime('%Y')

    def month(self):
        return self.published.strftime('%b')

    def day(self):
        return self.published.strftime('%d')

    def countWords(self):
        return readtime.of_text(self.body)

    def get_absolute_url(self):
        return reverse('article:details', args=[str(self.id)])


class Comment(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.article}'

pages/templates/pages/about.html
{% extends "base.html" %}

{% block content %}
  
    
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('static/images/bg_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">About</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section ftco-no-pt ftco-no-pb">
    	<div class="container">
    		<div class="row d-flex">
    			<div class="col-md-6 d-flex">
    				<div class="img img-video d-flex align-self-stretch align-items-center justify-content-center justify-content-md-end" style="background-image:url(static/images/about.jpg);">
    					<a href="https://vimeo.com/45830194" class="icon-video popup-vimeo d-flex justify-content-center align-items-center">
    						<span class="icon-play"></span>
    					</a>
    				</div>
    			</div>
    			<div class="col-md-6 pl-md-5 py-md-5">
    				<div class="row justify-content-start pt-3 pb-3">
		          <div class="col-md-12 heading-section ftco-animate">
		          	<span class="subheading">Welcome to News24</span>
		            <h2 class="mb-4">We give you the best articles you want.</h2>
		            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
		            <div class="tabulation-2 mt-4">
									<ul class="nav nav-pills nav-fill d-md-flex d-block">
									  <li class="nav-item mb-md-0 mb-2">
									    <a class="nav-link active py-2" data-toggle="tab" href="#home1">Our Mission</a>
									  </li>
									  <li class="nav-item px-lg-2 mb-md-0 mb-2">
									    <a class="nav-link py-2" data-toggle="tab" href="#home2">Our Vision</a>
									  </li>
									  <li class="nav-item">
									    <a class="nav-link py-2 mb-md-0 mb-2" data-toggle="tab" href="#home3">Our Value</a>
									  </li>
									</ul>
									<div class="tab-content bg-light rounded mt-2">
									  <div class="tab-pane container p-0 active" id="home1">
									  	<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
									  </div>
									  <div class="tab-pane container p-0 fade" id="home2">
									  	<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
									  </div>
									  <div class="tab-pane container p-0 fade" id="home3">
									  	<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
									  </div>
									</div>
								</div>
		          </div>
		        </div>
	        </div>
        </div>
    	</div>
    </section>

    <section class="ftco-section testimony-section">
      <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-7 text-center heading-section ftco-animate">
          	<span class="subheading">Testimonial</span>
            <h2 class="mb-4">Happy Clients</h2>
          </div>
        </div>
        <div class="row ftco-animate">
          <div class="col-md-12">
            <div class="carousel-testimony owl-carousel ftco-owl">
              <div class="item">
                <div class="testimony-wrap py-4">
                  <div class="text">
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <div class="d-flex align-items-center">
                    	<div class="user-img" style="background-image: url(images/person_1.jpg)"></div>
                    	<div class="pl-3">
		                    <p class="name">Roger Scott</p>
		                    <span class="position">Marketing Manager</span>
		                  </div>
	                  </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="testimony-wrap py-4">
                  <div class="text">
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <div class="d-flex align-items-center">
                    	<div class="user-img" style="background-image: url(images/person_2.jpg)"></div>
                    	<div class="pl-3">
		                    <p class="name">Roger Scott</p>
		                    <span class="position">Marketing Manager</span>
		                  </div>
	                  </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="testimony-wrap py-4">
                  <div class="text">
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <div class="d-flex align-items-center">
                    	<div class="user-img" style="background-image: url(images/person_3.jpg)"></div>
                    	<div class="pl-3">
		                    <p class="name">Roger Scott</p>
		                    <span class="position">Marketing Manager</span>
		                  </div>
	                  </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="testimony-wrap py-4">
                  <div class="text">
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <div class="d-flex align-items-center">
                    	<div class="user-img" style="background-image: url(images/person_1.jpg)"></div>
                    	<div class="pl-3">
		                    <p class="name">Roger Scott</p>
		                    <span class="position">Marketing Manager</span>
		                  </div>
	                  </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="testimony-wrap py-4">
                  <div class="text">
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <div class="d-flex align-items-center">
                    	<div class="user-img" style="background-image: url(images/person_2.jpg)"></div>
                    	<div class="pl-3">
		                    <p class="name">Roger Scott</p>
		                    <span class="position">Marketing Manager</span>
		                  </div>
	                  </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  

{% endblock content %}

pages/templates/pages/category.html
{% extends "base.html" %} 
{% load staticfiles %} 
{% block content %}
<div
  class="hero-wrap js-fullheight"
  style="background-image: url('static/images/bg_1.jpg');"
  data-stellar-background-ratio="0.5"
>
  <div class="overlay"></div>
  <div class="container">
    <div
      class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
      data-scrollax-parent="true"
    >
      <div class="col-md-12 ftco-animate">
        <h2 class="subheading">Hello! Welcome to</h2>
        <h1 class="mb-4 mb-md-0">News24</h1>
        <div class="row">
          <div class="col-md-7">
            <div class="text">
              <p>
                Far far away, behind the word mountains, far from the countries
                Vokalia and Consonantia, there live the blind texts. Separated
                they live in Bookmarksgrove right at the coast of the Semantics,
                a large language ocean.
              </p>
              <div class="mouse">
                <a href="#posts" class="mouse-icon">
                  <div class="mouse-wheel">
                    <span class="ion-ios-arrow-round-down"></span>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<section class="ftco-section" id="posts">
  <div class="container">
    <div class="row text-center">
      <h1 class="mb-5 font-weight-bold">All news in {{category.name}}</h1>
    </div>
    <hr />
    <div class="row">
      <div class="col-md-12">
        {% for article in category.article_set.all %}
        <div class="case">
          <div class="row">
            <div class="col-md-6 col-lg-6 col-xl-8 d-flex">
              <a href=" {% url 'article:details' article.id %}">
                <img src="{{article.image.url}}" class="img w-100 mb-3 mb-md-0" />
              </a>
            </div>
            <div class="col-md-6 col-lg-6 col-xl-4 d-flex">
              <div class="text w-100 pl-md-3">
                <span class="subheading">{{article.category.name}}</span>
                <h2><a href="{% url 'article:details' article.id %}">{{article.title}}</a></h2>
                {% if article.author == request.user %}
                <ul class="media-social list-unstyled">
                  <li class="ftco-animate">
                    <a
                      href="{% url 'article:edit' article.id %}"
                      class="p-2"
                      style="width: 80px;"
                      >Edit
                    </a>
                  </li>
                  <li class="ftco-animate">
                    <a
                      href="{% url 'article:delete' article.id %}"
                      class="p-1"
                      style="width: 80px;"
                      >Delete</a
                    >
                  </li>
                </ul>
                {% endif %}

                <div class="meta">
                  <p class="mb-0"><a>{{article.pub}}</a> | 
                    <a>{{article.countWords}}</a>
                  </p>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="row mt-5">
      <div class="col text-center">
        <div class="block-27">
          <ul class="pagination float-right">
         {% if page_obj.paginator.num_pages %}
        <li class="current page-item p-2">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </li>
        {% endif %}    
        {% if page_obj.has_previous %}

          <a href="?page=1" class="page-link">&laquo; first</a>

        
          <a href="?page={{ page_obj.previous_page_number }}" class="page-link"
            >previous</a
          >

        {% endif %} 
        
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="page-link"
          >next</a
        >
        <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link"
          >last &raquo;</a
        >
        {% endif %}
      </ul>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

pages/templates/pages/contact.html
{% extends "base.html" %}

{% block content %}

    
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('images/bg_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Contact us</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section contact-section">
      <div class="container">
        <div class="row d-flex mb-5 contact-info">
          <div class="col-md-12 mb-4">
            <h2 class="h3">Contact Information</h2>
          </div>
          <div class="w-100"></div>
          <div class="col-md-3">
            <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
          </div>
          <div class="col-md-3">
            <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
          </div>
          <div class="col-md-3">
            <p><span>Email:</span> <a href="mailto:info@yoursite.com">a.ahmed.chy@gmail.com</a></p>
          </div>
          <div class="col-md-3">
            <p><span>Website</span> <a href="#">yoursite.com</a></p>
          </div>
        </div>
        <div class="row block-9 no-gutters">
          <div class="col-lg-6 order-md-last d-flex">
            <form action="#" class="bg-light p-4 p-md-5 contact-form">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Name">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Email">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Subject">
              </div>
              <div class="form-group">
                <textarea name="" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
              </div>
            </form>
          
          </div>

          <div class="col-lg-6 d-flex">
          	<div id="map" class="bg-white"></div>
          </div>
        </div>
      </div>
    </section>
   
    
{% endblock content %}

pages/templates/pages/list_ajax.html
<div class="container"> 
    
    <hr />
    <div class="row">
      <div class="col-md-12">
        {% for article in articles %}
        <div class="case">
          <div class="row">
            <div class="col-md-6 col-lg-6 col-xl-8 d-flex">
              <a href=" {% url 'article:details' article.id %}">
                <img src="{{article.image.url}}" class="img w-100 mb-3 mb-md-0" />
              </a>
            </div>
            <div class="col-md-6 col-lg-6 col-xl-4 d-flex">
              <div class="text w-100 pl-md-3">
                <span class="subheading">{{article.category.name}}</span>
                <h2><a href="{% url 'article:details' article.id %}">{{article.title}}</a></h2>
                {% if article.author == request.user %}
                <ul class="media-social list-unstyled">
                  <li class="ftco-animate">
                    <a
                      href="{% url 'article:edit' article.id %}"
                      class="p-2"
                      style="width: 80px;"
                      >Edit
                    </a>
                  </li>
                  <li class="ftco-animate">
                    <a
                      href="{% url 'article:delete' article.id %}"
                      class="p-1"
                      style="width: 80px;"
                      >Delete</a
                    >
                  </li>
                </ul>
                {% endif %}

                <div class="meta">
                  <p class="mb-0"><a>{{article.pub}}</a> | 
                    <a>{{article.countWords}}</a>
                  </p>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

pages/templates/pages/tag.html
{% extends "base.html" %} 
{% load staticfiles %} 
{% block content %}
<div
  class="hero-wrap js-fullheight"
  style="background-image: url('static/images/bg_1.jpg');"
  data-stellar-background-ratio="0.5"
>
  <div class="overlay"></div>
  <div class="container">
    <div
      class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
      data-scrollax-parent="true"
    >
      <div class="col-md-12 ftco-animate">
        <h2 class="subheading">Hello! Welcome to</h2>
        <h1 class="mb-4 mb-md-0">News24</h1>
        <div class="row">
          <div class="col-md-7">
            <div class="text">
              <p>
                Far far away, behind the word mountains, far from the countries
                Vokalia and Consonantia, there live the blind texts. Separated
                they live in Bookmarksgrove right at the coast of the Semantics,
                a large language ocean.
              </p>
              <div class="mouse">
                <a href="#posts" class="mouse-icon">
                  <div class="mouse-wheel">
                    <span class="ion-ios-arrow-round-down"></span>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<section class="ftco-section" id="posts">
  <div class="container">
    <div class="row text-center">
      <h1 class="mb-5 font-weight-bold">All news in {{tag.name}} </h1>
    </div>
    <hr />
    <div class="row">
      <div class="col-md-12">
        {% for article in articles %}
        <div class="case">
          <div class="row">
            <div class="col-md-6 col-lg-6 col-xl-8 d-flex">
              <a href=" {% url 'article:details' article.id %}">
                <img src="{{article.image.url}}" class="img w-100 mb-3 mb-md-0" />
              </a>
            </div>
            <div class="col-md-6 col-lg-6 col-xl-4 d-flex">
              <div class="text w-100 pl-md-3">
                <span class="subheading">{{article.tag.name}}</span>
                <h2><a href="{% url 'article:details' article.id %}">{{article.title}}</a></h2>
                {% if article.author == request.user %}
                <ul class="media-social list-unstyled">
                  <li class="ftco-animate">
                    <a
                      href="{% url 'article:edit' article.id %}"
                      class="p-2"
                      style="width: 80px;"
                      >Edit
                    </a>
                  </li>
                  <li class="ftco-animate">
                    <a
                      href="{% url 'article:delete' article.id %}"
                      class="p-1"
                      style="width: 80px;"
                      >Delete</a
                    >
                  </li>
                </ul>
                {% endif %}

                <div class="meta">
                  <p class="mb-0"><a>{{article.pub}}</a> | 
                    <a>{{article.countWords}}</a>
                  </p>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="row mt-5">
      <div class="col text-center">
        <div class="block-27">
          <ul class="pagination float-right">
         {% if page_obj.paginator.num_pages %}
        <li class="current page-item p-2">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </li>
        {% endif %}    
        {% if page_obj.has_previous %}

          <a href="?page=1" class="page-link">&laquo; first</a>

        
          <a href="?page={{ page_obj.previous_page_number }}" class="page-link"
            >previous</a
          >

        {% endif %} 
        
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="page-link"
          >next</a
        >
        <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link"
          >last &raquo;</a
        >
        {% endif %}
      </ul>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}