articles/urls.py
from django.urls import path
from . import views
from .sitemaps import ArticleSitemap
from .feeds import LatestArticlesFeed
from django.contrib.sitemaps.views import sitemap
app_name = 'articles'

sitemaps = {
    'articles': ArticleSitemap,
}
urlpatterns = [
    path('',views.ArticleListView.as_view(),name='list'),
    path('<uuid:pk>',
         views.ArticleDetailView.as_view(), name='details'),
    path('<uuid:pk>/edit', views.ArticleUpdateView.as_view(), name='edit'),
    path('<uuid:pk>/delete', views.ArticleDeleteView.as_view(), name='delete'),
    path('create',views.ArticleCreateView.as_view(),name = 'create'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('feed', LatestArticlesFeed(), name="feed"),
    path('search', views.article_search,name = "search"),
    path('react', views.react, name ="react")
    
]

newspaper_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
    path('articles/', include('articles.urls',namespace='article')),
]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from articles import views as article_views

urlpatterns = [
    #path('',views.Home.as_view(),name = 'home'),
    path('', article_views.article_list_with_ajax_pagination, name='home'),
    path('about',views.About.as_view(),name = 'about'),
    path('contact',views.Contact.as_view(),name = 'contact'),
    path('categories/<int:pk>',views.Category.as_view(),name = 'category'),
   # path('tags/<slug:tag_slug>/',views.tag,name = 'tag'),
    path('tags/<int:pk>', views.Tagged.as_view(), name='tag'),
]

newspaper_project/templates/base.html
<!DOCTYPE html>
{%load staticfiles %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
  <title>Newspaper App</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">

  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

  <link rel="stylesheet" href="{% static 'css/aos.css' %}">

  <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://kit.fontawesome.com/0b40333001.js" crossorigin="anonymous"></script>
  {% block externals %}
  {% endblock externals %}
</head>

<body>
  <nav class="navbar  px-md-0 navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a href="{% url 'home' %}" class=" navbar-brand">
        <img src="{% static 'images/live-news.png' %}" height="40px" alt="" />

      </a>


      <a class="navbar-brand" href="{% url 'home' %}">News24</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
        aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>
      <!-- <form method="GET" class="form-inline my-2 my-lg-0 navbar-link" action="">
        {% csrf_token %}
        <input class="form-control " type="text" placeholder="Search" aria-label="Search" name="data"
          style="width:70%; height: 5%;" />
        <button class="btn btn-success  my-sm-0 p-1 m-2" type="submit">
          Search
        </button>
      </form> -->
      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item " id="home"><a href="{% url 'home' %}" class="nav-link">Home</a></li>
          <li class="nav-item">
            <div class="dropdown nav-link">
              <a class="dropdown-toggle    ml-1" type="button" id="dropdownMenuButton"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Category
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for category in categories %}
                <a class="dropdown-item" href="{% url 'category' category.id %}">{{category.name}}</a>
                {% endfor %}
              </div>
            </div>
          </li>
          <li class="nav-item" id="articles"><a href="{% url 'article:list' %}" class="nav-link">Articles</a></li>
          <li class="nav-item" id="team"><a href="{% url 'about' %}" class="nav-link">Team</a></li>
          <li class="nav-item" id="contact"><a href="{% url 'contact' %}" class="nav-link">Contact</a></li>
          <li class="nav-item navbar-brand">
            <a href="{% url 'articles:search' %}" class="nav-link">
           <img src="{% static 'images/search.png'%}" height="30px" alt="">
          </a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <div class=" nav-link  mr-2  text-uppercase font-weight-bold">
              Welcome
            </div>

          </li>
          <li class="nav-item">
            <div class="dropdown mr-1 ">
              <button class="btn btn-secondary dropdown-toggle mr-sm-3 my-2 p-1" type="button" id="dropdownMenuButton"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-arrow-circle-down"></i>
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'article:create' %}">Add Article</a>
              </div>
            </div>
          </li>
          <li class="nav-item">
            <a class=" nav-link btn  btn-info  text-white" href="javascript:{gotoLogout()}">Logout</a>
            <form id="logout" action="{% url 'account_logout' %}" method="POST">
              {% csrf_token %}
              <input type="hidden" />
            </form>
          </li>
          <li class="nav-item">
            <a href="{% url 'articles:feed'%}" class="nav-link ml-4  font-weight-bold text-white p-1"
             > <img src="{% static 'images/rss.png'%}" alt="" height="30px">
         </a>
          </li>
          {% else %}
          <li class="nav-item mr-1">
            <a class="nav-link  btn btn-success text-white" href="{% url 'account_login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class=" nav-link btn ml-1 btn-primary text-white" href="{% url 'account_signup' %}">Register</a>
          </li>
          {% endif %}

          
        </ul>
        
      </div>
      <!-- <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">

        </ul>
      </div> -->
    </div>
  </nav>
  {% block content %}

  {% endblock content %}
  <footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="logo"><a href="#">News<span>24</span>.</a></h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the
              blind texts.</p>
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
              <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
              <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
              <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">latest News</h2>
            <div class="block-21 mb-4 d-flex">
              <a class="img mr-4 rounded" style="background-image:url('static/images/image_1.jpg');"></a>
              <div class="text">
                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                <div class="meta">
                  <div><a href="#"></span> Oct. 16, 2019</a></div>
                  <div><a href="#"></span> Admin</a></div>
                  <div><a href="#"></span> 19</a></div>
                </div>
              </div>
            </div>
            <div class="block-21 mb-4 d-flex">
              <a class="img mr-4 rounded" style="background-image:url('static/images/image_2.jpg');"></a>
              <div class="text">
                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                <div class="meta">
                  <div><a href="#"></span> Oct. 16, 2019</a></div>
                  <div><a href="#"></span> Admin</a></div>
                  <div><a href="#"></span> 19</a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4 ml-md-5">
            <h2 class="ftco-heading-2">Information</h2>
            <ul class="list-unstyled">
              <li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Home</a></li>
              <li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>About</a></li>
              <li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Articles</a></li>
              <li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Contact</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">Have a Questions?</h2>
            <div class="block-23 mb-3">
              <ul>
                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San
                    Francisco, California, USA</span></li>
                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                <li><a href="#"><span class="icon icon-envelope"></span><span
                      class="text">info@yourdomain.com</span></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">

          
        </div>
      </div>
    </div>
  </footer>
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
      <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
      <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
        stroke="#F96D00" /></svg></div>


  <script src="{% static 'js/jquery.min.js' %}"></script>
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script> 
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false">
  </script>
  <script src="{% static 'js/google-map.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <script type="text/javascript">
    function gotoLogout() {
     // console.log("logout worked!! ");
      document.getElementById("logout").submit();
    }
  </script>
  <script>
var csrftoken = Cookies.get('csrftoken');
function csrfSafeMethod(method) 
  {
  // these HTTP methods do not require CSRF protection
  return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
$.ajaxSetup({
beforeSend: function(xhr, settings) {
if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
xhr.setRequestHeader("X-CSRFToken", csrftoken);
}
}
});     

  $(document).ready(
  function()
  { 
    {% block domready %}
    {% endblock %}
  });
</script>

  {% block externalScripts %} {% endblock externalScripts %}
</body>

</html>